-- ##############################
-- CREATE TABLE
-- ##############################

-- CHANGE DATABSE TO portfolio-projects
USE [portfolio-projects];

-- CREATE RETAIL SALES TABLE
DROP TABLE IF EXISTS dbo.RETAIL_SALES_ANALYSIS;
CREATE TABLE [dbo].[RETAIL_SALES_ANALYSIS] (
    [ORDER_ID]          VARCHAR(50)  NOT NULL,
    [CUSTOMER_ID]       VARCHAR(50)  NULL,
    [PRODUCT_CATEGORY]  VARCHAR(50)  NULL,
    [REGION]            VARCHAR(50)  NULL,
    [ORDER_DATE]        DATETIME     NULL,
    [QUANTITY]          INT          NULL,
    [UNIT_PRICE]        FLOAT        NULL,
    [TOTAL_SALES]       FLOAT        NULL,
    [PROFIT]            FLOAT        NULL,
    CONSTRAINT [PK_RETAIL_SALES_ANALYSIS] PRIMARY KEY CLUSTERED ([ORDER_ID] ASC)
);

-- INSERT VALUES INTO RETAIL_SALES_ANALYSIS (IMPORT FROM CSV)
-- OPEN THE TERMINAL AND CD INTO THE FOLDER CONTAINING THE FILE TO UPLOAD
-- MOVE CSV FILE TO DOCKER CONTAINER VIA 'docker cp retail_sales_analysis.csv sql:/' THEN RUN THE FOLLOWING COMMAND
BULK INSERT dbo.RETAIL_SALES_ANALYSIS
FROM '/retail_sales_analysis.csv'
WITH
(
    FORMAT='CSV',
    FIRSTROW=2 -- COLUMN NAMES ALREADY CREATED SO SET TO START ON SECOND LINE
);

-- VERIFY RESULT
SELECT TOP 100 *
FROM RETAIL_SALES_ANALYSIS;