-- EXPLORATORY ANALYSIS

-- CHANGE DATABSE TO portfolio-projects
USE [portfolio-projects];


-- VIEW DATA
SELECT TOP 100 *
FROM RETAIL_SALES_ANALYSIS;


-- SUMMARY STATS
SELECT COUNT(*) AS NO_RECORDS
    ,COUNT(DISTINCT CUSTOMER_ID) AS TOT_NO_CUST
    ,COUNT(DISTINCT PRODUCT_CATEGORY) AS TOT_NO_CAT
    ,MIN(ORDER_DATE) AS MIN_DT
    ,MAX(ORDER_DATE) AS MIN_DT
    ,MIN(QUANTITY) AS MIN_QTY 
    ,AVG(QUANTITY) AS AVG_QTY 
    ,MAX(QUANTITY) AS MAX_QTY 
    ,MIN(UNIT_PRICE) AS MIN_UNIT_PRC
    ,AVG(UNIT_PRICE) AS AVG_UNIT_PRC 
    ,MAX(UNIT_PRICE) AS MAX_UNIT_PRC
    ,MIN(TOTAL_SALES) AS MIN_TTL_SALES
    ,AVG(TOTAL_SALES) AS AVG_TTL_SALES
    ,MAX(TOTAL_SALES) AS MAX_TTL_SALES
    ,MIN(PROFIT) AS MIN_PROFIT
    ,AVG(PROFIT) AS AVG_PROFIT
    ,MAX(PROFIT) AS MAX_PROFIT
FROM RETAIL_SALES_ANALYSIS;


-- TOP CUSTOMERS BY SALES
SELECT CUSTOMER_ID
    ,ROUND(SUM(TOTAL_SALES),0) AS TTL_SALES
    ,COUNT(DISTINCT ORDER_ID) AS TTL_ORDERS
    ,ROUND(AVG(TOTAL_SALES),0) AS AOV -- AVERAGE ORDER VALUE
    ,ROUND(AVG(QUANTITY),0) AS UPT -- UNITS PER TRANSACTION
FROM RETAIL_SALES_ANALYSIS
GROUP BY CUSTOMER_ID
ORDER BY TTL_SALES DESC;
