-- ##############################
-- EXPLORATORY ANALYSIS
-- ##############################

-- CHANGE DATABSE TO portfolio-projects
USE [portfolio-projects];

-- VIEW DATA
SELECT TOP 100 *
FROM RETAIL_SALES_ANALYSIS;

-- SUMMARY STATS
SELECT COUNT(*) AS NO_RECORDS
    ,COUNT(DISTINCT CUSTOMER_ID) AS TOT_NO_CUST
    ,COUNT(DISTINCT PRODUCT_CATEGORY) AS TOT_NO_CAT
    ,MIN(ORDER_DATE) AS MIN_DT
    ,MAX(ORDER_DATE) AS MIN_DT
    ,MIN(QUANTITY) AS MIN_QTY 
    ,AVG(QUANTITY) AS AVG_QTY 
    ,MAX(QUANTITY) AS MAX_QTY 
    ,MIN(UNIT_PRICE) AS MIN_UNIT_PRC
    ,AVG(UNIT_PRICE) AS AVG_UNIT_PRC 
    ,MAX(UNIT_PRICE) AS MAX_UNIT_PRC
    ,MIN(TOTAL_SALES) AS MIN_TTL_SALES
    ,AVG(TOTAL_SALES) AS AVG_TTL_SALES
    ,MAX(TOTAL_SALES) AS MAX_TTL_SALES
    ,MIN(PROFIT) AS MIN_PROFIT
    ,AVG(PROFIT) AS AVG_PROFIT
    ,MAX(PROFIT) AS MAX_PROFIT
FROM RETAIL_SALES_ANALYSIS;


-- ##############################
-- CUSTOMER METRICS
-- ##############################

-- TOP CUSTOMERS BY SALES
SELECT TOP 10 CUSTOMER_ID
    ,ROUND(SUM(TOTAL_SALES),0) AS TTL_SALES
    ,COUNT(DISTINCT ORDER_ID) AS TTL_ORDERS
    ,ROUND(AVG(TOTAL_SALES),0) AS AOV -- AVERAGE ORDER VALUE
    ,ROUND(AVG(QUANTITY),0) AS UPT -- UNITS PER TRANSACTION
FROM RETAIL_SALES_ANALYSIS
GROUP BY CUSTOMER_ID
ORDER BY TTL_SALES DESC;

-- PRODUCT CATEGORY % SALES BY CUSTOMER (TOP 10)
WITH a AS (
SELECT CUSTOMER_ID
    ,COALESCE(ROUND(SUM(CASE WHEN PRODUCT_CATEGORY = 'Furniture' THEN TOTAL_SALES END),0),0) AS FURN_TTL_SALES
    ,COALESCE(ROUND(SUM(CASE WHEN PRODUCT_CATEGORY = 'Clothing' THEN TOTAL_SALES END),0),0) AS CLOTH_TTL_SALES
    ,COALESCE(ROUND(SUM(CASE WHEN PRODUCT_CATEGORY = 'Electronics' THEN TOTAL_SALES END),0),0) AS ELEC_TTL_SALES
    ,COALESCE(ROUND(SUM(CASE WHEN PRODUCT_CATEGORY = 'Grocery' THEN TOTAL_SALES END),0),0) AS GROC_TTL_SALES
    ,COALESCE(ROUND(SUM(TOTAL_SALES),0),0) AS TTL_SALES
FROM RETAIL_SALES_ANALYSIS 
GROUP BY CUSTOMER_ID
)

SELECT TOP 10 CUSTOMER_ID
    ,ROUND(SUM(FURN_TTL_SALES) * 100 /SUM(TTL_SALES),0) AS FURN_PCT
    ,ROUND(SUM(CLOTH_TTL_SALES) * 100 /SUM(TTL_SALES),0) AS CLOTH_PCT
    ,ROUND(SUM(ELEC_TTL_SALES) * 100 /SUM(TTL_SALES),0) AS ELEC_PCT
    ,ROUND(SUM(GROC_TTL_SALES) * 100 /SUM(TTL_SALES),0) AS GROC_PCT
    ,SUM(TTL_SALES) AS TTL_SALES
FROM a
GROUP BY CUSTOMER_ID
ORDER BY TTL_SALES DESC;

-- DAYS BETWEEN ORDERS
WITH a AS (
    SELECT CUSTOMER_ID
        ,ORDER_DATE
        ,LAG(ORDER_DATE) OVER (PARTITION BY CUSTOMER_ID ORDER BY ORDER_DATE) AS PREV_ORDER_DT
    FROM RETAIL_SALES_ANALYSIS
)

SELECT AVG(DATEDIFF(DAY, PREV_ORDER_DT, ORDER_DATE)) AS AVG_DAYS_BETWEEN_ORDERS
FROM a
WHERE PREV_ORDER_DT IS NOT NULL;


-- ##############################
-- CATEGORY METRICS
-- ##############################

-- MOST PROFITABLE CATEGORY
SELECT TOP 1 PRODUCT_CATEGORY
    ,SUM(PROFIT) AS TTL_PROFIT
FROM RETAIL_SALES_ANALYSIS
GROUP BY PRODUCT_CATEGORY
ORDER BY TTL_PROFIT DESC;

-- CATEGORY WITH LEAST AMOUNT OF SALES
SELECT TOP 1 PRODUCT_CATEGORY
    ,SUM(TOTAL_SALES) AS TTL_SALES
FROM RETAIL_SALES_ANALYSIS
GROUP BY PRODUCT_CATEGORY
ORDER BY TTL_SALES ASC;

-- LARGEST ORDER WITHIN EACH CATEGORY, WITHIN EACH REGION
SELECT ORDER_ID
    ,PRODUCT_CATEGORY
    ,REGION
    ,TTL_SALES
FROM (
    SELECT ORDER_ID
        ,PRODUCT_CATEGORY
        ,REGION
        ,SUM(TOTAL_SALES) AS TTL_SALES
        ,RANK() OVER(PARTITION BY REGION, PRODUCT_CATEGORY ORDER BY SUM(TOTAL_SALES) DESC) AS REGION_PROD_RANK
    FROM RETAIL_SALES_ANALYSIS
    GROUP BY ORDER_ID, REGION, PRODUCT_CATEGORY
    ) AS TOP_ORDERS
WHERE REGION_PROD_RANK = 1
ORDER BY REGION, TTL_SALES DESC;

-- ##############################
-- REGION METRICS
-- ##############################

-- TOTAL CUSTOMERS IN EACH REGION
SELECT REGION
    ,COUNT(DISTINCT CUSTOMER_ID) AS TOT_CUST
FROM RETAIL_SALES_ANALYSIS
WHERE CUSTOMER_ID IS NOT NULL
GROUP BY REGION
ORDER BY TOT_CUST DESC;

-- TOP SPENDING CUSTOMER IN EACH REGION
WITH a AS (
    SELECT REGION
        ,CUSTOMER_ID
        ,SUM(TOTAL_SALES) AS TOT_SALES
        ,RANK() OVER(PARTITION BY REGION ORDER BY SUM(TOTAL_SALES) DESC) AS REGION_RANK
    FROM RETAIL_SALES_ANALYSIS
    GROUP BY REGION, CUSTOMER_ID
    HAVING SUM(TOTAL_SALES) IS NOT NULL
)

SELECT REGION
    ,CUSTOMER_ID
    ,ROUND(TOT_SALES,0) AS TOT_SALES
FROM a 
WHERE REGION_RANK = 1
ORDER BY TOT_SALES DESC;

-- CUMMULATIVE DAILY SALES BY REGION
SELECT REGION
    ,ORDER_DATE
    ,TTL_SALES
    ,SUM(TTL_SALES) OVER (
        PARTITION BY REGION 
        ORDER BY ORDER_DATE 
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS CUMULATIVE_SALES
FROM (
    SELECT REGION
        ,CAST(ORDER_DATE AS DATE) AS ORDER_DATE
        ,SUM(TOTAL_SALES) AS TTL_SALES
    FROM RETAIL_SALES_ANALYSIS
    GROUP BY REGION, CAST(ORDER_DATE AS DATE)
    ) AS SALES_BY_DT
ORDER BY REGION, ORDER_DATE;


